### PR TITLE
Readme update File

### LINKED ISSUE #7: [ReadMe] Write an effective readMe file
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by todak2000**
## Description
Read me file updated to reflect details of the project

### CODE REVIEW

**Review by byruzyayandy1 — APPROVED** [review]
Good job

**Review by albert85 — APPROVED** [review]
LGTM

**Review by Stephen-Kamau — APPROVED** [review]

**Review by AminuIsrael — APPROVED** [review]
This is very precise, good Job

**Review by AminuIsrael — APPROVED** [review]
This is very precise, good Job

**Pull request merged**
