### PR TITLE
Set up user authentication for WasteCoin

### LINKED ISSUE #4: [User Authentication Design] Design of login, registration, verification, password reset page
**Is your feature request related to a problem? Please describe.**
Users need these authentication pages to access their profile account both new and existing users

**Describe the solution you'd like**
- User will be able to login for existing users, new users will be able to create an account and verify the details they supplied

### LINKED ISSUE #5: [FEATURE] Register and Validate User on WasteCoin
**Is your feature request related to a problem? Please describe.**
A register and signup page is important for user verification and user registration

**Describe the solution you'd like**
It takes user data, stores it in a DataBase and Verify that User

**Describe alternatives you've considered**
Using Django, a python web framework to Implement the solution

### PR DESCRIPTION
**Pull request by AminuIsrael**
## Description
Please include a summary of the change and relevant motivation and context.
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Stephen-Kamau — DISMISSED** [review]
Great work @AminuIsrael

**Review by todak2000 — DISMISSED** [review]
I guess that is as best as you could clean it. Well done. Thanks

**Review by albert85 — DISMISSED** [review]
I'm approving because it needed to be merge, but I expect the login API to return user details but I can't find in the documentation, hopefully, its return user details

**Review by todak2000 — CHANGES_REQUESTED** [review]
Please make the login api return all users details except password so it can be passed into the dashboard. Well done. thats  the only adjustment.. Thanks

**Comment by AminuIsrael** [comment]
> I'm approving because it needed to be merge, but I expect the login API to return user details but I can't find in the documentation, hopefully, its return user details

I've effected the change, check the documentation

**Comment by AminuIsrael** [comment]
> Please make the login api return all users details except password so it can be passed into the dashboard. Well done. thats the only adjustment.. Thanks

This change has been effected already

**Review by todak2000 — APPROVED** [review]
Great!

**Review by byruzyayandy1 — APPROVED** [review]
Cool

**Review by albert85 — APPROVED** [review]
LGTM

**Pull request merged**
